### ISSUE TITLE
Setup react-router

### ISSUE THREAD

**Issue by chasedeanda** [jwilson573/ufc_trivia#8]
Setup initial routing for:
- `/` Home
- `/play/:game_mode/categories` Categories
- `/play/:game_mode/:category_id` Gameboard
- `/leaderboards` Select a game mode maybe?
- `/leaderboards/:game_mode` Leaderboard for game mode

**Comment by jwilson573** [comment]
Woikin on it boss.

**Comment by jwilson573** [comment]
I got the router working. I don't have all the routes setup yet since we don't have pages for them just yet. I did make a Home component that just displays an H1 tag showing "Splash Screen Placeholder". "Tap Out" will take you to that page. /new-game goes to the page with the octagon on it. I figure there we can have them select the game mode.

Also, played with RWD. Had it looking real good on the iPhone 7 and 7+, but I added the Tap Out at the end and it started messing with stuff of course lol. I want the Tap Out link to be justified to the right, but it's kinda tricky I guess where I have it set.
